# Generated by Django 5.1.6 on 2025-02-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('rut_institucion', models.CharField(max_length=12, unique=True)),
                ('nombre_institucion', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('sitio_web', models.CharField(blank=True, max_length=50, null=True)),
                ('representante_legal', models.CharField(max_length=50)),
                ('telefono_institucion', models.CharField(max_length=12)),
                ('correo_institucion', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
