# Generated by Django 5.1.6 on 2025-02-14 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='correo_institucion',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nro_aula', models.CharField(max_length=10)),
                ('tamaño', models.IntegerField(blank=True, null=True)),
                ('cantidad_alumnos', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('rut_profesor', models.CharField(max_length=12, unique=True)),
                ('nombre_profesor', models.CharField(max_length=50)),
                ('apellido_profesor', models.CharField(max_length=50)),
                ('correo_profesor', models.EmailField(max_length=50, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('antecedentes_medicos', models.CharField(blank=True, max_length=100, null=True)),
                ('area_docencia', models.CharField(max_length=50)),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.aula')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.profesor')),
            ],
        ),
    ]
