# Generated by Django 5.1.6 on 2025-03-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0002_alter_institucion_correo_institucion_aula_profesor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('nro_aula', 'id_institucion')},
        ),
    ]
