# Generated by Django 5.1.6 on 2025-04-23 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0003_alter_aula_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
