# Generated by Django 5.1.6 on 2025-06-02 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0004_institucion_created_at_institucion_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo_IoT',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('mac_dispositivo', models.CharField(max_length=17, unique=True)),
                ('tipo_dispositivo', models.CharField(choices=[('1', 'Dosimetro de voz'), ('2', 'Sonometro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo_IoT_Aula',
            fields=[
                ('id_dispositivo_aula', models.AutoField(primary_key=True, serialize=False)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.aula')),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.dispositivo_iot')),
            ],
            options={
                'unique_together': {('id_dispositivo', 'id_aula')},
            },
        ),
        migrations.CreateModel(
            name='Dispositivo_IoT_Profesor',
            fields=[
                ('id_dispositivo_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.dispositivo_iot')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.profesor')),
            ],
            options={
                'unique_together': {('id_dispositivo', 'id_profesor')},
            },
        ),
    ]
