# Generated by Django 5.1.6 on 2025-06-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0005_dispositivo_iot_dispositivo_iot_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo_iot',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('1', 'Dosímetro de Voz'), ('2', 'Registrador de Variables Ambientales')], max_length=1),
        ),
    ]
