# Generated by Django 5.1.6 on 2025-06-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0006_alter_dispositivo_iot_tipo_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo_iot_aula',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispositivo_iot_profesor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
