# Generated by Django 5.1.6 on 2025-06-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0007_dispositivo_iot_aula_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo_iot_aula',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='dispositivo_iot_profesor',
            name='activo',
        ),
        migrations.AddField(
            model_name='dispositivo_iot',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
