# Generated by Django 5.1.6 on 2025-06-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0008_remove_dispositivo_iot_aula_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='antecedentes_medicos',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='area_docencia',
            field=models.CharField(max_length=300),
        ),
    ]
