# Generated by Django 5.1.6 on 2025-06-05 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0008_remove_dispositivo_iot_aula_activo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispositivo_iot_profesor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dispositivo_iot_profesor',
            name='id_dispositivo',
        ),
        migrations.RemoveField(
            model_name='dispositivo_iot_profesor',
            name='id_profesor',
        ),
        migrations.RemoveField(
            model_name='dispositivo_iot',
            name='activo',
        ),
        migrations.CreateModel(
            name='Relacion_Aula',
            fields=[
                ('id_relacion_aula', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=17)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.aula')),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.dispositivo_iot')),
            ],
            options={
                'unique_together': {('id_aula', 'mac')},
            },
        ),
        migrations.CreateModel(
            name='Relacion_Profesor',
            fields=[
                ('id_relacion_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=17)),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.dispositivo_iot')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.profesor')),
            ],
            options={
                'unique_together': {('id_profesor', 'mac')},
            },
        ),
        migrations.DeleteModel(
            name='Dispositivo_IoT_Aula',
        ),
        migrations.DeleteModel(
            name='Dispositivo_IoT_Profesor',
        ),
    ]
