# Generated by Django 5.1.6 on 2025-06-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0009_alter_dispositivo_iot_profesor_unique_together_and_more'),
        ('web_monitor', '0009_alter_profesor_antecedentes_medicos_and_more'),
    ]

    operations = [
    ]
