# Generated by Django 5.1.6 on 2025-06-09 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0010_merge_20250605_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula_CO2',
            fields=[
                ('id_aula_co2', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('co2', models.FloatField()),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.aula')),
            ],
            options={
                'unique_together': {('fecha_hora', 'id_aula')},
            },
        ),
        migrations.CreateModel(
            name='Aula_Humedad',
            fields=[
                ('id_aula_humedad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('humedad', models.FloatField()),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.aula')),
            ],
            options={
                'unique_together': {('fecha_hora', 'id_aula')},
            },
        ),
        migrations.CreateModel(
            name='Aula_Ruido',
            fields=[
                ('id_aula_ruido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ruido', models.FloatField()),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.aula')),
            ],
            options={
                'unique_together': {('fecha_hora', 'id_aula')},
            },
        ),
        migrations.CreateModel(
            name='Aula_Temperatura',
            fields=[
                ('id_aula_temperatura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField()),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.aula')),
            ],
            options={
                'unique_together': {('fecha_hora', 'id_aula')},
            },
        ),
        migrations.CreateModel(
            name='Profesor_Voz',
            fields=[
                ('id_profesor_voz', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Freq', models.FloatField()),
                ('Intensidad', models.FloatField()),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_monitor.profesor')),
            ],
            options={
                'unique_together': {('fecha_hora', 'id_profesor')},
            },
        ),
    ]
