# Generated by Django 5.1.6 on 2025-06-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0011_aula_co2_aula_humedad_aula_ruido_aula_temperatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula_co2',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='aula_humedad',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='aula_ruido',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='aula_temperatura',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
