# Generated by Django 5.1.6 on 2025-06-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0012_alter_aula_co2_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre_institucion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='representante_legal',
            field=models.CharField(max_length=100),
        ),
    ]
