# Generated by Django 5.1.6 on 2025-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_monitor', '0013_alter_institucion_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor_voz',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
